# Original
# https://github.com/FSou1/deploy-deno-to-heroku/blob/7d7dc8a3873047a7f1bc63fe782b4de80cd886a9/.github/workflows/main.yml

name: Deno

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }} # runs a test on Ubuntu, Windows and macOS

    strategy:
      matrix:
        deno: ["v1.x", "nightly"]
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }} # tests across multiple Deno versions

      - name: Cache Dependencies
        run: deno cache deps.ts

      - name: Lint
        run: deno lint --unstable
        
      - name: Unit tests
        run: deno test --allow-env --allow-read
